### ISSUE TITLE
Translating doesnt separate the item name from the gui title 

### ISSUE THREAD

**Issue by akkini1** [JamCoreModding/utility-belt#1]
The item name Utility belt and the title in the GUI uses the same line in the lang file, unlike how they'd normally be separated, and the GUI title would be put under `container.utility-belt` for example, this proves quite an annoyance since you arent able to replace just one of them like you'd normally would.
In my case i wanted to remove the text for the GUI for a resource pack, so this is a minor annoyance

**Comment by Jamalam360** [comment]
They are separate in new release, thanks for reporting

**Comment by Jamalam360** [comment]
Unfortunately 1.20.1 is out of support, since 1.20.4 was a huge rewrite and backporting it would be too much effort.

Side note: Utility Belt 1.20.1 is probably going to be archived on Curseforge and Modrinth, because it has too many bugs. Modpacks that already include it will be unaffected, but it won't appear on the websites anymore.
